// apps/react-showcase/src/App.tsx
import { useState, useCallback } from "react";
import { BrowserRouter, Routes, Route, NavLink } from "react-router-dom";
import { Sun, Moon } from "lucide-react";
import { Button } from "./components/ui/button";
import Dashboard from "./pages/Dashboard";
import DesignSystem from "./pages/DesignSystem";

// ---------------------------------------------------------------------------
// Header with Navigation
// ---------------------------------------------------------------------------

function Header() {
  const [dark, setDark] = useState(true);

  const toggleTheme = () => {
    const next = !dark;
    const html = document.documentElement;
    html.classList.toggle("dark", next);
    // Sync AG Grid theme mode — it reads data-ag-theme-mode, not .dark class
    html.dataset.agThemeMode = next ? "dark" : "light";
    setDark(next);
  };

  const linkClass = useCallback(
    ({ isActive }: { isActive: boolean }) =>
      `text-sm font-medium transition-colors hover:text-foreground ${isActive ? "text-foreground" : "text-muted-foreground"}`,
    [],
  );

  return (
    <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-6">
        <div className="flex items-center gap-8">
          <h1 className="text-lg font-semibold tracking-tight">MarketsUI</h1>
          <nav className="flex items-center gap-6">
            <NavLink to="/" className={linkClass} end>
              Dashboard
            </NavLink>
            <NavLink to="/design-system" className={linkClass}>
              Design System
            </NavLink>
          </nav>
        </div>
        <Button variant="ghost" size="icon" onClick={toggleTheme} aria-label="Toggle theme">
          {dark ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}
        </Button>
      </div>
    </header>
  );
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

export default function App() {
  return (
    <BrowserRouter>
      <div className="min-h-screen bg-background">
        <Header />
        <main className="mx-auto max-w-7xl px-6 py-8">
          <Routes>
            <Route path="/" element={<Dashboard />} />
            <Route path="/design-system" element={<DesignSystem />} />
          </Routes>
        </main>
      </div>
    </BrowserRouter>
  );
}

// apps/angular-showcase/src/app/app.component.ts
import { Component, ChangeDetectionStrategy, signal, DOCUMENT, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { ButtonModule } from 'primeng/button';

@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, ButtonModule],
  template: `
    <!-- Header nav shell -->
    <header class="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur">
      <div class="mx-auto flex h-14 max-w-7xl items-center justify-between px-6">
        <div class="flex items-center gap-8">
          <h1 class="text-lg font-semibold tracking-tight">MarketsUI</h1>
          <nav class="flex items-center gap-6">
            <a routerLink="/" routerLinkActive="nav-active" [routerLinkActiveOptions]="{ exact: true }"
              class="nav-link">Dashboard</a>
            <a routerLink="/design-system" routerLinkActive="nav-active"
              class="nav-link">Design System</a>
          </nav>
        </div>
        <button pButton [text]="true" [rounded]="true"
          [icon]="isDark() ? 'pi pi-sun' : 'pi pi-moon'"
          (click)="toggleTheme()" class="!text-foreground"></button>
      </div>
    </header>

    <!-- Routed content -->
    <main class="mx-auto max-w-7xl px-6 py-8">
      <router-outlet />
    </main>
  `,
  styles: [`
    :host { display: block; min-height: 100vh; }

    .nav-link {
      font-size: 14px;
      font-weight: 500;
      color: hsl(var(--muted-foreground));
      text-decoration: none;
      transition: color 0.15s;
    }
    .nav-link:hover {
      color: hsl(var(--foreground));
    }
    .nav-active {
      color: hsl(var(--foreground));
    }
  `],
})
export class AppComponent {
  private document = inject(DOCUMENT);
  isDark = signal(true);

  toggleTheme(): void {
    const html = this.document.documentElement;
    const dark = html.classList.toggle('dark');
    // Sync AG Grid theme mode — it reads data-ag-theme-mode, not .dark class
    html.dataset['agThemeMode'] = dark ? 'dark' : 'light';
    this.isDark.set(dark);
  }
}
