// apps/react-showcase/src/pages/Dashboard.tsx
import { useState } from "react";
import {
  CreditCard,
  Apple,
  Check,
  Star,
  Search,
  Plus,
  Minus,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  MoreHorizontal,
  Archive,
  Clock,
  Sparkles,
  Globe,
  ArrowUp,
  Loader2,
  CheckCircle2,
  Paperclip,
  Info,
  Mic,
} from "lucide-react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Separator } from "../components/ui/separator";
import { Switch } from "../components/ui/switch";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";
import { Badge } from "../components/ui/badge";
import { Checkbox } from "../components/ui/checkbox";
import { Slider } from "../components/ui/slider";
import { RadioGroup, RadioGroupItem } from "../components/ui/radio-group";
import { Avatar, AvatarFallback } from "../components/ui/avatar";
import { Textarea } from "../components/ui/textarea";
import { ToggleGroup, ToggleGroupItem } from "../components/ui/toggle-group";

// ---------------------------------------------------------------------------
// Column 0 — Single tall payment card
// ---------------------------------------------------------------------------

function PaymentCard() {
  const [method, setMethod] = useState<"card" | "paypal" | "apple">("card");

  return (
    <Card>
      <CardHeader>
        <CardTitle>Payment Method</CardTitle>
        <CardDescription>
          All transactions are secure and encrypted.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Payment type toggles */}
        <div className="grid grid-cols-3 gap-4">
          <Button
            variant={method === "card" ? "outline" : "ghost"}
            className={`flex flex-col items-center gap-1 h-auto py-3 ${method === "card" ? "!border-primary" : ""}`}
            onClick={() => setMethod("card")}
          >
            <CreditCard className="h-5 w-5" />
            <span className="text-xs">Card</span>
          </Button>
          <Button
            variant={method === "paypal" ? "outline" : "ghost"}
            className={`flex flex-col items-center gap-1 h-auto py-3 ${method === "paypal" ? "!border-primary" : ""}`}
            onClick={() => setMethod("paypal")}
          >
            <svg className="h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
              <path d="M7.076 21.337H2.47a.641.641 0 0 1-.633-.74L4.944.901C5.026.382 5.474 0 5.998 0h7.46c2.57 0 4.578.543 5.69 1.81 1.01 1.15 1.304 2.42 1.012 4.287-.023.143-.047.288-.077.437-.983 5.05-4.349 6.797-8.647 6.797h-2.19c-.524 0-.968.382-1.05.9l-1.12 7.106z" />
            </svg>
            <span className="text-xs">Paypal</span>
          </Button>
          <Button
            variant={method === "apple" ? "outline" : "ghost"}
            className={`flex flex-col items-center gap-1 h-auto py-3 ${method === "apple" ? "!border-primary" : ""}`}
            onClick={() => setMethod("apple")}
          >
            <Apple className="h-5 w-5" />
            <span className="text-xs">Apple</span>
          </Button>
        </div>

        {/* Name on Card */}
        <div className="space-y-2">
          <Label htmlFor="name">Name on Card</Label>
          <Input id="name" placeholder="John Doe" />
        </div>

        {/* Card Number + CVV */}
        <div className="grid grid-cols-4 gap-4">
          <div className="col-span-3 space-y-2">
            <Label htmlFor="card-number">Card Number</Label>
            <Input id="card-number" placeholder="1234 5678 9012 3456" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="cvv">CVV</Label>
            <Input id="cvv" placeholder="123" />
          </div>
        </div>
        <p className="text-xs text-muted-foreground">
          Enter your 16-digit number.
        </p>

        {/* Month + Year */}
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label>Month</Label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="MM" />
              </SelectTrigger>
              <SelectContent>
                {Array.from({ length: 12 }, (_, i) => {
                  const v = String(i + 1).padStart(2, "0");
                  return (
                    <SelectItem key={v} value={v}>
                      {v}
                    </SelectItem>
                  );
                })}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label>Year</Label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="YYYY" />
              </SelectTrigger>
              <SelectContent>
                {[2024, 2025, 2026, 2027, 2028, 2029].map((y) => (
                  <SelectItem key={y} value={String(y)}>
                    {y}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <Separator />

        {/* Billing Address */}
        <div className="space-y-2">
          <p className="text-sm font-medium">Billing Address</p>
          <p className="text-xs text-muted-foreground">
            The billing address associated with your payment method.
          </p>
          <div className="flex items-center space-x-2 pt-1">
            <Checkbox id="same-address" defaultChecked />
            <Label htmlFor="same-address" className="text-sm font-normal">
              Same as shipping address
            </Label>
          </div>
        </div>

        <Separator />

        {/* Comments */}
        <div className="space-y-2">
          <Label>Comments</Label>
          <Textarea placeholder="Add any additional comments" />
        </div>
      </CardContent>
      <CardFooter className="flex gap-2">
        <Button className="flex-1">Submit</Button>
        <Button variant="outline" className="flex-1">
          Cancel
        </Button>
      </CardFooter>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Column 1 — 5 cards
// ---------------------------------------------------------------------------

function NoTeamMembersCard() {
  return (
    <Card>
      <CardContent className="flex flex-col items-center pt-6 pb-6 text-center">
        <div className="flex -space-x-3 mb-4">
          <Avatar className="h-10 w-10 border-2 border-background">
            <AvatarFallback className="text-xs">CN</AvatarFallback>
          </Avatar>
          <Avatar className="h-10 w-10 border-2 border-background">
            <AvatarFallback className="text-xs">LR</AvatarFallback>
          </Avatar>
          <Avatar className="h-10 w-10 border-2 border-background">
            <AvatarFallback className="text-xs">ER</AvatarFallback>
          </Avatar>
        </div>
        <CardTitle className="text-sm mb-1">No Team Members</CardTitle>
        <CardDescription className="text-xs mb-4">
          Invite your team to collaborate on this project.
        </CardDescription>
        <Button variant="outline" size="sm">
          <Plus className="mr-1.5 h-3.5 w-3.5" />
          Invite Members
        </Button>
      </CardContent>
    </Card>
  );
}

function StatusBadgesRow() {
  return (
    <div className="rounded-lg border bg-card p-3 flex flex-wrap gap-2">
      <Badge variant="outline" className="gap-1.5">
        <span className="h-2 w-2 rounded-full bg-primary animate-pulse" />
        Syncing
      </Badge>
      <Badge variant="outline" className="gap-1.5">
        <span className="h-2 w-2 rounded-full bg-primary animate-pulse" />
        Updating
      </Badge>
      <Badge variant="outline" className="gap-1.5">
        <span className="h-2 w-2 rounded-full bg-primary animate-pulse" />
        Loading
      </Badge>
    </div>
  );
}

function SendMessageRow() {
  return (
    <div className="rounded-lg border bg-card p-2">
      <div className="flex items-center gap-2">
        <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0">
          <Plus className="h-4 w-4" />
        </Button>
        <Input
          placeholder="Send a message..."
          className="h-8 text-sm border-0 shadow-none focus-visible:ring-0"
        />
        <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0">
          <Mic className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}

function PriceRangeCard() {
  const [range, setRange] = useState([200, 800]);
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium">Price Range</CardTitle>
        <CardDescription className="text-xs">
          Set your budget range (${range[0]} - {range[1]}).
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Slider
          defaultValue={[200, 800]}
          min={0}
          max={1000}
          step={10}
          onValueChange={setRange}
        />
      </CardContent>
    </Card>
  );
}

function BottomStackCard() {
  return (
    <Card>
      <CardContent className="space-y-3 pt-6">
        {/* Search input */}
        <div className="flex items-center gap-2">
          <div className="relative flex-1">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input placeholder="Search..." className="h-9 pl-8 text-sm" />
          </div>
          <span className="text-xs text-muted-foreground whitespace-nowrap">
            12 results
          </span>
        </div>

        {/* URL input */}
        <div className="flex items-center rounded-md border border-input">
          <span className="px-3 text-sm text-muted-foreground bg-muted border-r border-input rounded-l-md py-1.5">
            https://
          </span>
          <Input
            placeholder="example.com"
            className="border-0 shadow-none focus-visible:ring-0 h-auto py-1.5 text-sm flex-1"
          />
          <Info className="h-4 w-4 text-muted-foreground mr-2.5 shrink-0" />
        </div>

        {/* AI chat input */}
        <Input
          placeholder="Ask, Search or Chat..."
          className="h-9 text-sm"
        />

        {/* Auto / usage row */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Plus className="h-3 w-3" />
            <span>Auto</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted-foreground">52% used</span>
            <Button
              size="icon"
              className="h-7 w-7 rounded-full"
            >
              <ArrowUp className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>

        {/* Username input */}
        <div className="relative">
          <Input defaultValue="@shadcn" className="h-9 pr-8 text-sm" />
          <CheckCircle2 className="absolute right-2.5 top-2.5 h-4 w-4 text-green-500" />
        </div>
      </CardContent>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Column 2 — 4 cards
// ---------------------------------------------------------------------------

function BrowserUrlBar() {
  return (
    <div className="rounded-lg border bg-card p-3">
      <div className="flex items-center gap-2">
        <Globe className="h-4 w-4 text-muted-foreground shrink-0" />
        <span className="text-sm text-muted-foreground">https://</span>
        <span className="flex-1" />
        <Star className="h-4 w-4 text-muted-foreground shrink-0" />
      </div>
    </div>
  );
}

function AuthProfileCard() {
  return (
    <Card>
      <CardContent className="space-y-3 pt-6">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-1">
            <p className="text-sm font-medium">Two-factor authentication</p>
            <p className="text-xs text-muted-foreground">
              Verify via email or phone number.
            </p>
          </div>
          <Button variant="outline" size="sm" className="shrink-0">
            Enable
          </Button>
        </div>
        <Separator />
        <div className="flex items-center gap-3">
          <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />
          <span className="text-sm flex-1">
            Your profile has been verified.
          </span>
          <ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" />
        </div>
      </CardContent>
    </Card>
  );
}

function AppearanceSettings() {
  return (
    <div className="rounded-lg border bg-card p-3">
      <p className="text-sm font-medium">Appearance Settings</p>
    </div>
  );
}

function ComputeEnvironmentCard() {
  const [gpus, setGpus] = useState(8);
  return (
    <Card>
      <CardContent className="space-y-4 pt-6">
        {/* Compute Environment */}
        <div className="space-y-1">
          <p className="text-sm font-medium">Compute Environment</p>
          <p className="text-xs text-muted-foreground">
            Select the compute environment for your cluster.
          </p>
        </div>
        <RadioGroup defaultValue="k8s" className="space-y-3">
          <div className="flex items-start space-x-3 rounded-md border border-primary p-3">
            <RadioGroupItem value="k8s" id="k8s" className="mt-0.5" />
            <div>
              <Label htmlFor="k8s" className="text-sm font-medium">
                Kubernetes
              </Label>
              <p className="text-xs text-muted-foreground">
                Run GPU workloads on a K8s configured cluster. This is the
                default.
              </p>
            </div>
          </div>
          <div className="flex items-start space-x-3 rounded-md border p-3 opacity-50">
            <RadioGroupItem value="vm" id="vm" disabled className="mt-0.5" />
            <div>
              <Label htmlFor="vm" className="text-sm font-medium">
                Virtual Machine
              </Label>
              <p className="text-xs text-muted-foreground">
                Access a VM configured cluster to run workloads. (Coming soon)
              </p>
            </div>
          </div>
        </RadioGroup>

        <Separator />

        {/* Number of GPUs */}
        <div className="space-y-1">
          <p className="text-sm font-medium">Number of GPUs</p>
          <p className="text-xs text-muted-foreground">
            You can add more later.
          </p>
        </div>
        <div className="flex items-center justify-center gap-4">
          <Button
            variant="outline"
            size="icon"
            className="h-8 w-8"
            onClick={() => setGpus((c) => Math.max(0, c - 1))}
          >
            <Minus className="h-4 w-4" />
          </Button>
          <span className="w-8 text-center text-lg font-semibold tabular-nums">
            {gpus}
          </span>
          <Button
            variant="outline"
            size="icon"
            className="h-8 w-8"
            onClick={() => setGpus((c) => c + 1)}
          >
            <Plus className="h-4 w-4" />
          </Button>
        </div>

        <Separator />

        {/* Wallpaper Tinting */}
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-0.5">
            <p className="text-sm font-medium">Wallpaper Tinting</p>
            <p className="text-xs text-muted-foreground">
              Allow the wallpaper to be tinted.
            </p>
          </div>
          <Switch defaultChecked />
        </div>
      </CardContent>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Column 3 — 6 cards (xl only)
// ---------------------------------------------------------------------------

function PromptContextCard() {
  return (
    <Card>
      <CardContent className="space-y-3 pt-6">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-muted-foreground" />
          <Button variant="outline" size="sm" className="text-xs">
            Add context
          </Button>
        </div>
        <Input
          placeholder="Ask, search, or make anything..."
          className="h-9 text-sm"
        />
        <Separator />
        <div className="flex items-center gap-2">
          <Paperclip className="h-4 w-4 text-muted-foreground shrink-0" />
          <span className="text-xs text-muted-foreground">Auto</span>
          <div className="flex items-center gap-1 text-xs text-muted-foreground">
            <Globe className="h-3 w-3" />
            <span>All Sources</span>
          </div>
          <span className="flex-1" />
          <Button size="icon" className="h-7 w-7 rounded-full">
            <ArrowUp className="h-3.5 w-3.5" />
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

function ActionsBar() {
  return (
    <div className="rounded-lg border bg-card p-2">
      <div className="flex items-center gap-1">
        <Button variant="ghost" size="icon" className="h-8 w-8">
          <ChevronLeft className="h-4 w-4" />
        </Button>
        <Button variant="ghost" size="sm" className="h-8 text-xs">
          Archive
        </Button>
        <Button variant="ghost" size="sm" className="h-8 text-xs">
          Report
        </Button>
        <Button variant="ghost" size="sm" className="h-8 text-xs">
          Snooze
        </Button>
        <Button variant="ghost" size="icon" className="h-8 w-8">
          <MoreHorizontal className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}

function TermsRow() {
  return (
    <div className="rounded-lg border bg-card p-3">
      <div className="flex items-center space-x-2">
        <Checkbox id="terms" defaultChecked />
        <Label htmlFor="terms" className="text-sm font-normal leading-snug">
          I agree to the terms and conditions
        </Label>
      </div>
    </div>
  );
}

function PaginationCopilotRow() {
  return (
    <div className="rounded-lg border bg-card p-2">
      <div className="flex items-center gap-1">
        {[1, 2, 3].map((n) => (
          <Button
            key={n}
            variant={n === 1 ? "default" : "ghost"}
            size="icon"
            className="h-8 w-8 text-xs"
          >
            {n}
          </Button>
        ))}
        <Button variant="ghost" size="icon" className="h-8 w-8">
          <ChevronLeft className="h-4 w-4" />
        </Button>
        <Button variant="ghost" size="icon" className="h-8 w-8">
          <ChevronRight className="h-4 w-4" />
        </Button>
        <span className="flex-1" />
        <Sparkles className="h-4 w-4 text-muted-foreground" />
        <Button variant="outline" size="sm" className="h-8 text-xs gap-1">
          Copilot
          <ChevronDown className="h-3 w-3" />
        </Button>
      </div>
    </div>
  );
}

function SurveyCard() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm font-medium">
          How did you hear about us?
        </CardTitle>
        <CardDescription className="text-xs">
          Select the option that best describes how you found us.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ToggleGroup
          type="single"
          defaultValue="social"
          variant="outline"
          className="grid grid-cols-2 gap-2"
        >
          <ToggleGroupItem
            value="social"
            className="text-xs h-9 rounded-md data-[state=on]:bg-primary data-[state=on]:text-primary-foreground"
          >
            Social Media
          </ToggleGroupItem>
          <ToggleGroupItem
            value="search"
            className="text-xs h-9 rounded-md"
          >
            Search Engine
          </ToggleGroupItem>
          <ToggleGroupItem
            value="referral"
            className="text-xs h-9 rounded-md"
          >
            Referral
          </ToggleGroupItem>
          <ToggleGroupItem
            value="other"
            className="text-xs h-9 rounded-md"
          >
            Other
          </ToggleGroupItem>
        </ToggleGroup>
      </CardContent>
    </Card>
  );
}

function ProcessingCard() {
  return (
    <Card>
      <CardContent className="flex flex-col items-center text-center pt-6 pb-6 space-y-4">
        <Loader2 className="h-10 w-10 animate-spin text-muted-foreground" />
        <div className="space-y-1">
          <p className="text-sm font-medium">Processing your request</p>
          <p className="text-xs text-muted-foreground">
            Please wait while we process your request. Do not refresh the page.
          </p>
        </div>
        <Button variant="outline" size="sm" className="text-xs">
          Cancel
        </Button>
      </CardContent>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Dashboard Page
// ---------------------------------------------------------------------------

export default function Dashboard() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      {/* Column 0 */}
      <div className="flex flex-col gap-6">
        <PaymentCard />
      </div>

      {/* Column 1 */}
      <div className="flex flex-col gap-6">
        <NoTeamMembersCard />
        <StatusBadgesRow />
        <SendMessageRow />
        <PriceRangeCard />
        <BottomStackCard />
      </div>

      {/* Column 2 */}
      <div className="flex flex-col gap-6">
        <BrowserUrlBar />
        <AuthProfileCard />
        <AppearanceSettings />
        <ComputeEnvironmentCard />
      </div>

      {/* Column 3 */}
      <div className="hidden xl:flex flex-col gap-6">
        <PromptContextCard />
        <ActionsBar />
        <TermsRow />
        <PaginationCopilotRow />
        <SurveyCard />
        <ProcessingCard />
      </div>
    </div>
  );
}

// apps/angular-showcase/src/app/pages/dashboard.component.ts
import { Component, ChangeDetectionStrategy, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { SelectModule } from 'primeng/select';
import { ToggleSwitchModule } from 'primeng/toggleswitch';
import { TextareaModule } from 'primeng/textarea';
import { CheckboxModule } from 'primeng/checkbox';
import { RadioButtonModule } from 'primeng/radiobutton';
import { SliderModule } from 'primeng/slider';

/* ── Types ── */
interface Option { label: string; value: string; }

/* ── Data ── */
const MONTHS: Option[] = Array.from({ length: 12 }, (_, i) => {
  const v = String(i + 1).padStart(2, '0');
  return { label: v, value: v };
});
const YEARS: Option[] = [2024, 2025, 2026, 2027, 2028, 2029].map(y => ({
  label: String(y), value: String(y),
}));

@Component({
  selector: 'app-dashboard',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    FormsModule,
    ButtonModule,
    InputTextModule,
    SelectModule,
    ToggleSwitchModule,
    TextareaModule,
    CheckboxModule,
    RadioButtonModule,
    SliderModule,
  ],
  template: `
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">

      <!-- ═══════ Column 0 — Payment Method ═══════ -->
      <div class="flex flex-col gap-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Payment Method</h3>
            <p class="card-desc">All transactions are secure and encrypted.</p>
          </div>
          <div class="card-body space-y-4">

            <!-- Payment type toggles -->
            <div class="grid grid-cols-3 gap-4">
              @for (m of paymentMethods; track m.value) {
                <button
                  class="payment-selector"
                  [class.selected]="paymentMethod() === m.value"
                  (click)="paymentMethod.set(m.value)"
                >
                  @if (m.value === 'card') { <i class="pi pi-credit-card text-lg"></i> }
                  @if (m.value === 'paypal') {
                    <svg class="h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M7.076 21.337H2.47a.641.641 0 0 1-.633-.74L4.944.901C5.026.382 5.474 0 5.998 0h7.46c2.57 0 4.578.543 5.69 1.81 1.01 1.15 1.304 2.42 1.012 4.287-.023.143-.047.288-.077.437-.983 5.05-4.349 6.797-8.647 6.797h-2.19c-.524 0-.968.382-1.05.9l-1.12 7.106z"/>
                    </svg>
                  }
                  @if (m.value === 'apple') { <i class="pi pi-apple text-lg"></i> }
                  <span class="text-xs">{{ m.label }}</span>
                </button>
              }
            </div>

            <!-- Name on Card -->
            <div class="space-y-2">
              <label class="field-label">Name on Card</label>
              <input pInputText placeholder="John Doe" class="w-full" />
            </div>

            <!-- Card Number + CVV -->
            <div class="grid grid-cols-4 gap-4">
              <div class="col-span-3 space-y-2">
                <label class="field-label">Card Number</label>
                <input pInputText placeholder="1234 5678 9012 3456" class="w-full" />
              </div>
              <div class="space-y-2">
                <label class="field-label">CVV</label>
                <input pInputText placeholder="123" class="w-full" />
              </div>
            </div>
            <p class="text-xs text-[hsl(var(--muted-foreground))]">Enter your 16-digit number.</p>

            <!-- Month + Year -->
            <div class="grid grid-cols-2 gap-4">
              <div class="space-y-2">
                <label class="field-label">Month</label>
                <p-select [options]="months" placeholder="MM" optionLabel="label" optionValue="value" styleClass="w-full" />
              </div>
              <div class="space-y-2">
                <label class="field-label">Year</label>
                <p-select [options]="years" placeholder="YYYY" optionLabel="label" optionValue="value" styleClass="w-full" />
              </div>
            </div>

            <!-- Separator -->
            <div class="separator-h"></div>

            <!-- Billing Address -->
            <div class="space-y-2">
              <p class="text-sm font-medium text-[hsl(var(--foreground))]">Billing Address</p>
              <p class="text-xs text-[hsl(var(--muted-foreground))]">The billing address associated with your payment method.</p>
              <div class="flex items-center space-x-2 pt-1">
                <p-checkbox [binary]="true" [(ngModel)]="shippingSame" inputId="same-address" />
                <label for="same-address" class="text-sm font-normal text-[hsl(var(--foreground))]">Same as shipping address</label>
              </div>
            </div>

            <!-- Separator -->
            <div class="separator-h"></div>

            <!-- Comments -->
            <div class="space-y-2">
              <label class="field-label">Comments</label>
              <textarea pTextarea placeholder="Add any additional comments" class="w-full" [rows]="3"></textarea>
            </div>
          </div>

          <div class="card-footer flex gap-2">
            <button pButton label="Submit" class="flex-1 primary-btn"></button>
            <button pButton label="Cancel" [outlined]="true" class="flex-1 outline-btn"></button>
          </div>
        </div>
      </div>

      <!-- ═══════ Column 1 — Team, Badges, Message, Price, Bottom Stack ═══════ -->
      <div class="flex flex-col gap-6">

        <!-- No Team Members -->
        <div class="card">
          <div class="card-body flex flex-col items-center text-center">
            <div class="flex -space-x-3 mb-4">
              <div class="avatar border-2 border-[hsl(var(--background))]">CN</div>
              <div class="avatar border-2 border-[hsl(var(--background))]">LR</div>
              <div class="avatar border-2 border-[hsl(var(--background))]">ER</div>
            </div>
            <p class="text-sm font-semibold mb-1 text-[hsl(var(--foreground))]">No Team Members</p>
            <p class="text-xs mb-4 text-[hsl(var(--muted-foreground))]">Invite your team to collaborate on this project.</p>
            <button pButton label="Invite Members" icon="pi pi-plus" [outlined]="true" size="small" class="outline-btn"></button>
          </div>
        </div>

        <!-- Status Badges -->
        <div class="small-card flex flex-wrap gap-2">
          <span class="badge-outline">
            <span class="h-2 w-2 rounded-full bg-[hsl(var(--primary))] animate-pulse"></span>
            Syncing
          </span>
          <span class="badge-outline">
            <span class="h-2 w-2 rounded-full bg-[hsl(var(--primary))] animate-pulse"></span>
            Updating
          </span>
          <span class="badge-outline">
            <span class="h-2 w-2 rounded-full bg-[hsl(var(--primary))] animate-pulse"></span>
            Loading
          </span>
        </div>

        <!-- Send Message -->
        <div class="small-card !p-2">
          <div class="flex items-center gap-2">
            <button pButton icon="pi pi-plus" [text]="true" size="small" class="ghost-btn shrink-0 !h-8 !w-8"></button>
            <input pInputText placeholder="Send a message..." class="flex-1 msg-input" />
            <button pButton icon="pi pi-microphone" [text]="true" size="small" class="ghost-btn shrink-0 !h-8 !w-8"></button>
          </div>
        </div>

        <!-- Price Range -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Price Range</h3>
            <p class="text-xs text-[hsl(var(--muted-foreground))]">Set your budget range ({{ '$' + sliderRange()[0] }} - {{ sliderRange()[1] }}).</p>
          </div>
          <div class="card-body">
            <p-slider [ngModel]="sliderRange()" (ngModelChange)="sliderRange.set($event)" [range]="true" [min]="0" [max]="1000" [step]="10" styleClass="w-full" />
          </div>
        </div>

        <!-- Bottom Stack -->
        <div class="card">
          <div class="card-body space-y-3">

            <!-- Search input -->
            <div class="flex items-center gap-2">
              <div class="relative flex-1">
                <i class="pi pi-search absolute left-2.5 top-2.5 text-sm text-[hsl(var(--muted-foreground))]"></i>
                <input pInputText placeholder="Search..." class="w-full h-9 pl-8 text-sm" />
              </div>
              <span class="text-xs text-[hsl(var(--muted-foreground))] whitespace-nowrap">12 results</span>
            </div>

            <!-- URL input -->
            <div class="flex items-center rounded-md border border-[hsl(var(--border))]">
              <span class="px-3 text-sm text-[hsl(var(--muted-foreground))] bg-[hsl(var(--muted))] border-r border-[hsl(var(--border))] rounded-l-md py-1.5">https://</span>
              <input pInputText placeholder="example.com" class="flex-1 url-input" />
              <i class="pi pi-info-circle text-sm text-[hsl(var(--muted-foreground))] mr-2.5 shrink-0"></i>
            </div>

            <!-- AI chat input -->
            <input pInputText placeholder="Ask, Search or Chat..." class="w-full h-9 text-sm" />

            <!-- Auto / usage row -->
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-1.5 text-xs text-[hsl(var(--muted-foreground))]">
                <i class="pi pi-plus text-xs"></i>
                <span>Auto</span>
              </div>
              <div class="flex items-center gap-2">
                <span class="text-xs text-[hsl(var(--muted-foreground))]">52% used</span>
                <button pButton icon="pi pi-arrow-up" class="primary-btn !h-7 !w-7 !rounded-full"></button>
              </div>
            </div>

            <!-- Username input -->
            <div class="relative">
              <input pInputText value="&#64;shadcn" class="w-full h-9 pr-8 text-sm" />
              <i class="pi pi-check-circle absolute right-2.5 top-2.5 text-sm" style="color: #22c55e;"></i>
            </div>
          </div>
        </div>
      </div>

      <!-- ═══════ Column 2 — Browser, Auth, Appearance, Compute ═══════ -->
      <div class="flex flex-col gap-6">

        <!-- Browser URL bar -->
        <div class="small-card">
          <div class="flex items-center gap-2">
            <i class="pi pi-globe text-sm text-[hsl(var(--muted-foreground))] shrink-0"></i>
            <span class="text-sm text-[hsl(var(--muted-foreground))]">https://</span>
            <span class="flex-1"></span>
            <i class="pi pi-star text-sm text-[hsl(var(--muted-foreground))] shrink-0"></i>
          </div>
        </div>

        <!-- Auth + Profile -->
        <div class="card">
          <div class="card-body space-y-3">
            <div class="flex items-start justify-between gap-4">
              <div class="space-y-1">
                <p class="text-sm font-medium text-[hsl(var(--foreground))]">Two-factor authentication</p>
                <p class="text-xs text-[hsl(var(--muted-foreground))]">Verify via email or phone number.</p>
              </div>
              <button pButton label="Enable" [outlined]="true" size="small" class="outline-btn shrink-0"></button>
            </div>
            <div class="separator-h"></div>
            <div class="flex items-center gap-3">
              <i class="pi pi-check-circle text-sm shrink-0" style="color: #22c55e;"></i>
              <span class="text-sm flex-1 text-[hsl(var(--foreground))]">Your profile has been verified.</span>
              <i class="pi pi-chevron-right text-sm text-[hsl(var(--muted-foreground))] shrink-0"></i>
            </div>
          </div>
        </div>

        <!-- Appearance Settings -->
        <div class="small-card">
          <p class="text-sm font-medium text-[hsl(var(--foreground))]">Appearance Settings</p>
        </div>

        <!-- Compute Environment + GPU + Wallpaper -->
        <div class="card">
          <div class="card-body space-y-4">

            <!-- Compute Environment -->
            <div class="space-y-1">
              <p class="text-sm font-medium text-[hsl(var(--foreground))]">Compute Environment</p>
              <p class="text-xs text-[hsl(var(--muted-foreground))]">Select the compute environment for your cluster.</p>
            </div>

            <div class="space-y-3">
              <div class="flex items-start space-x-3 rounded-md border border-[hsl(var(--primary))] p-3">
                <p-radioButton name="compute" value="kubernetes" [(ngModel)]="computeEnv" inputId="k8s" />
                <div>
                  <label for="k8s" class="text-sm font-medium text-[hsl(var(--foreground))]">Kubernetes</label>
                  <p class="text-xs text-[hsl(var(--muted-foreground))]">Run GPU workloads on a K8s configured cluster. This is the default.</p>
                </div>
              </div>
              <div class="flex items-start space-x-3 rounded-md border border-[hsl(var(--border))] p-3 opacity-50">
                <p-radioButton name="compute" value="vm" [(ngModel)]="computeEnv" inputId="vm" [disabled]="true" />
                <div>
                  <label for="vm" class="text-sm font-medium text-[hsl(var(--foreground))]">Virtual Machine</label>
                  <p class="text-xs text-[hsl(var(--muted-foreground))]">Access a VM configured cluster to run workloads. (Coming soon)</p>
                </div>
              </div>
            </div>

            <div class="separator-h"></div>

            <!-- Number of GPUs -->
            <div class="space-y-1">
              <p class="text-sm font-medium text-[hsl(var(--foreground))]">Number of GPUs</p>
              <p class="text-xs text-[hsl(var(--muted-foreground))]">You can add more later.</p>
            </div>
            <div class="flex items-center justify-center gap-4">
              <button pButton icon="pi pi-minus" [outlined]="true" size="small" class="outline-btn !h-8 !w-8"
                (click)="gpuCount.set(Math.max(0, gpuCount() - 1))"></button>
              <span class="w-8 text-center text-lg font-semibold tabular-nums text-[hsl(var(--foreground))]">{{ gpuCount() }}</span>
              <button pButton icon="pi pi-plus" [outlined]="true" size="small" class="outline-btn !h-8 !w-8"
                (click)="gpuCount.set(gpuCount() + 1)"></button>
            </div>

            <div class="separator-h"></div>

            <!-- Wallpaper Tinting -->
            <div class="flex items-center justify-between gap-4">
              <div class="space-y-0.5">
                <p class="text-sm font-medium text-[hsl(var(--foreground))]">Wallpaper Tinting</p>
                <p class="text-xs text-[hsl(var(--muted-foreground))]">Allow the wallpaper to be tinted.</p>
              </div>
              <p-toggleswitch [(ngModel)]="wallpaperTinting" />
            </div>
          </div>
        </div>
      </div>

      <!-- ═══════ Column 3 — xl only ═══════ -->
      <div class="hidden xl:flex flex-col gap-6">

        <!-- Prompt / Context -->
        <div class="card">
          <div class="card-body space-y-3">
            <div class="flex items-center gap-2">
              <i class="pi pi-sparkles text-sm text-[hsl(var(--muted-foreground))]"></i>
              <button pButton label="Add context" [outlined]="true" size="small" class="outline-btn !text-xs"></button>
            </div>
            <input pInputText placeholder="Ask, search, or make anything..." class="w-full h-9 text-sm" />
            <div class="separator-h"></div>
            <div class="flex items-center gap-2">
              <i class="pi pi-paperclip text-sm text-[hsl(var(--muted-foreground))] shrink-0"></i>
              <span class="text-xs text-[hsl(var(--muted-foreground))]">Auto</span>
              <div class="flex items-center gap-1 text-xs text-[hsl(var(--muted-foreground))]">
                <i class="pi pi-globe text-xs"></i>
                <span>All Sources</span>
              </div>
              <span class="flex-1"></span>
              <button pButton icon="pi pi-arrow-up" class="primary-btn !h-7 !w-7 !rounded-full"></button>
            </div>
          </div>
        </div>

        <!-- Actions bar -->
        <div class="small-card !p-2">
          <div class="flex items-center gap-1">
            <button pButton icon="pi pi-chevron-left" [text]="true" size="small" class="ghost-btn !h-8 !w-8"></button>
            <button pButton label="Archive" [text]="true" size="small" class="ghost-btn !h-8 !text-xs"></button>
            <button pButton label="Report" [text]="true" size="small" class="ghost-btn !h-8 !text-xs"></button>
            <button pButton label="Snooze" [text]="true" size="small" class="ghost-btn !h-8 !text-xs"></button>
            <button pButton icon="pi pi-ellipsis-h" [text]="true" size="small" class="ghost-btn !h-8 !w-8"></button>
          </div>
        </div>

        <!-- Terms -->
        <div class="small-card">
          <div class="flex items-center space-x-2">
            <p-checkbox [binary]="true" [(ngModel)]="termsAgreed" inputId="terms" />
            <label for="terms" class="text-sm font-normal leading-snug text-[hsl(var(--foreground))]">I agree to the terms and conditions</label>
          </div>
        </div>

        <!-- Pagination + Copilot -->
        <div class="small-card !p-2">
          <div class="flex items-center gap-1">
            @for (n of [1, 2, 3]; track n) {
              <button pButton [label]="'' + n" size="small"
                [class]="n === 1 ? 'primary-btn !h-8 !w-8 !text-xs' : 'ghost-btn !h-8 !w-8 !text-xs'"
                [text]="n !== 1">
              </button>
            }
            <button pButton icon="pi pi-chevron-left" [text]="true" size="small" class="ghost-btn !h-8 !w-8"></button>
            <button pButton icon="pi pi-chevron-right" [text]="true" size="small" class="ghost-btn !h-8 !w-8"></button>
            <span class="flex-1"></span>
            <i class="pi pi-sparkles text-sm text-[hsl(var(--muted-foreground))]"></i>
            <button pButton label="Copilot" icon="pi pi-chevron-down" iconPos="right" [outlined]="true" size="small" class="outline-btn !h-8 !text-xs !gap-1"></button>
          </div>
        </div>

        <!-- Survey -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title" style="font-size:0.875rem">How did you hear about us?</h3>
            <p class="card-desc" style="font-size:0.75rem">Select the option that best describes how you found us.</p>
          </div>
          <div class="card-body">
            <div class="grid grid-cols-2 gap-2">
              @for (opt of surveyOptions; track opt.value) {
                <button
                  class="survey-btn"
                  [class.survey-active]="surveyAnswer() === opt.value"
                  (click)="surveyAnswer.set(opt.value)"
                >{{ opt.label }}</button>
              }
            </div>
          </div>
        </div>

        <!-- Processing spinner -->
        <div class="card">
          <div class="card-body flex flex-col items-center text-center space-y-4">
            <i class="pi pi-spinner pi-spin text-[hsl(var(--muted-foreground))]" style="font-size: 2.5rem;"></i>
            <div class="space-y-1">
              <p class="text-sm font-medium text-[hsl(var(--foreground))]">Processing your request</p>
              <p class="text-xs text-[hsl(var(--muted-foreground))]">Please wait while we process your request. Do not refresh the page.</p>
            </div>
            <button pButton label="Cancel" [outlined]="true" size="small" class="outline-btn !text-xs"></button>
          </div>
        </div>
      </div>

    </div>
  `,
  styles: [`
    :host { display: block; }

    /* ── Card ── */
    .card {
      border-radius: 0.75rem;
      display: flex;
      flex-direction: column;
      gap: 1rem;
      padding-top: 1rem;
      padding-bottom: 1rem;
      overflow: hidden;
      background: hsl(var(--card));
      color: hsl(var(--card-foreground));
      box-shadow: inset 0 0 0 1px hsl(var(--foreground) / 0.1);
    }

    /* ── Card header ── */
    .card-header {
      display: grid;
      grid-auto-rows: min-content;
      gap: 0.25rem;
      padding: 0 1rem;
    }
    .card-title {
      font-size: 1rem;
      font-weight: 500;
      line-height: 1.375;
      color: hsl(var(--foreground));
      margin: 0;
    }
    .card-desc {
      font-size: 0.875rem;
      color: hsl(var(--muted-foreground));
      margin: 0;
    }

    /* ── Card body (= CardContent) ── */
    .card-body {
      padding: 0 1rem;
    }

    /* ── Card footer ── */
    .card-footer {
      display: flex;
      align-items: center;
      padding: 1rem;
      border-top: 1px solid hsl(var(--border));
      background: hsl(var(--muted) / 0.5);
      border-radius: 0 0 0.75rem 0.75rem;
    }
    .card:has(.card-footer) { padding-bottom: 0; }

    /* ── Small card / row ── */
    .small-card {
      border-radius: 0.5rem;
      border: 1px solid hsl(var(--border));
      background: hsl(var(--card));
      padding: 0.75rem;
    }

    /* ── Avatar ── */
    .avatar {
      display: flex;
      width: 2.5rem;
      height: 2.5rem;
      flex-shrink: 0;
      align-items: center;
      justify-content: center;
      border-radius: 9999px;
      background: hsl(var(--muted));
      color: hsl(var(--foreground));
      font-size: 0.75rem;
      font-weight: 500;
    }

    /* ── Badge outline ── */
    .badge-outline {
      display: inline-flex;
      align-items: center;
      gap: 0.375rem;
      border-radius: 9999px;
      border: 1px solid hsl(var(--border));
      padding: 0.125rem 0.625rem;
      font-size: 0.75rem;
      font-weight: 500;
      color: hsl(var(--foreground));
    }

    /* ── Field label ── */
    .field-label {
      display: block;
      font-size: 0.875rem;
      font-weight: 500;
      color: hsl(var(--foreground));
    }

    /* ── Payment selector ── */
    .payment-selector {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 4px;
      padding: 0.75rem 0;
      border-radius: calc(0.5rem - 2px);
      border: 1px solid hsl(var(--border));
      background: transparent;
      color: hsl(var(--foreground));
      cursor: pointer;
      transition: border-color 0.15s, background 0.15s;
    }
    .payment-selector:hover:not(.selected) {
      background: hsl(var(--muted) / 0.5);
    }
    .payment-selector.selected {
      border-color: hsl(var(--primary));
    }

    /* ── Separator horizontal ── */
    .separator-h {
      height: 1px;
      background: hsl(var(--border));
    }

    /* ── Survey toggle buttons ── */
    .survey-btn {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 2.25rem;
      border-radius: 0.375rem;
      border: 1px solid hsl(var(--border));
      background: transparent;
      color: hsl(var(--foreground));
      font-size: 0.75rem;
      font-weight: 500;
      cursor: pointer;
      transition: background 0.15s, color 0.15s, border-color 0.15s;
    }
    .survey-btn:hover:not(.survey-active) {
      background: hsl(var(--muted) / 0.5);
    }
    .survey-btn.survey-active {
      background: hsl(var(--primary));
      color: hsl(var(--primary-foreground));
      border-color: hsl(var(--primary));
    }

    /* ── URL input override ── */
    :host ::ng-deep .url-input.p-inputtext {
      border: none !important;
      box-shadow: none !important;
      border-radius: 0 0.375rem 0.375rem 0;
      height: auto;
      padding-top: 0.375rem;
      padding-bottom: 0.375rem;
      font-size: 0.875rem;
    }

    /* ── Message input override ── */
    :host ::ng-deep .msg-input.p-inputtext {
      height: 2rem;
      font-size: 0.875rem;
      border: 0 !important;
      box-shadow: none !important;
    }

    /* ── PrimeNG button variants ── */
    :host ::ng-deep .primary-btn.p-button {
      background: hsl(var(--primary));
      color: hsl(var(--primary-foreground));
      border-color: hsl(var(--primary));
    }
    :host ::ng-deep .primary-btn.p-button:hover {
      background: hsl(var(--primary) / 0.9);
      border-color: hsl(var(--primary) / 0.9);
    }

    :host ::ng-deep .outline-btn.p-button {
      background: transparent;
      color: hsl(var(--foreground));
      border-color: hsl(var(--border));
    }
    :host ::ng-deep .outline-btn.p-button:hover {
      background: hsl(var(--muted) / 0.5);
    }

    :host ::ng-deep .ghost-btn.p-button {
      background: transparent;
      color: hsl(var(--foreground));
      border-color: transparent;
    }
    :host ::ng-deep .ghost-btn.p-button:hover {
      background: hsl(var(--muted) / 0.5);
    }
  `],
})
export class DashboardComponent {
  readonly Math = Math;

  /* ── State (signals) ── */
  readonly paymentMethod = signal<string>('card');
  readonly termsAgreed = signal(true);
  readonly computeEnv = signal('kubernetes');
  readonly gpuCount = signal(8);
  readonly wallpaperTinting = signal(false);
  readonly surveyAnswer = signal('social');
  readonly sliderRange = signal([200, 800]);
  readonly shippingSame = signal(true);

  /* ── Static data ── */
  readonly paymentMethods = [
    { value: 'card', label: 'Card' },
    { value: 'paypal', label: 'Paypal' },
    { value: 'apple', label: 'Apple' },
  ];
  readonly months = MONTHS;
  readonly years = YEARS;
  readonly surveyOptions = [
    { label: 'Social Media', value: 'social' },
    { label: 'Search Engine', value: 'search' },
    { label: 'Referral', value: 'referral' },
    { label: 'Other', value: 'other' },
  ];
}
